### ISSUE TITLE
Source with different database than target database not working

### ISSUE THREAD

**Issue by nghildebrandt** [Tomme/dbt-athena#89]
Hi, I am wondering if the database property for sources is defined for dbt athena? After setting the database property in sources and running dbt run, it tries to build tables using my target database and not source database. I hope you can help with this, I have attached my sources file.  Thanks

To select from the source I call:
```   from {{source('fleetdog', 'raw_public_trips')}}```

My source is configured like this:
```
version:  2

sources:
  - name: fleetdog
    database: dataalpha
    quoting:
      database: true
    tables:
      - name: raw_public_trips
```

Error:
```
07:41:39  Runtime Error in model my_first_dbt_model (models/example/my_first_dbt_model.sql)
07:41:39    SYNTAX_ERROR: line 15:6: Table awsdatacatalog.fleetdog.raw_public_trips does not exist. 
```
